import { chromium } from 'playwright';
const B = 'http://localhost:8901';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, colorScheme: 'light' });
const page = await ctx.newPage();
const shot = (n) => page.screenshot({ path: `/home/user/audit/shots/${n}.png` });
page.on('pageerror', e => console.log('PAGE ERR:', String(e).slice(0,200)));

await page.goto(B + '/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(500);
await shot('00-splash');
await page.waitForTimeout(1400);           // splash auto-routes to onboarding
await shot('01-ob1');
await page.evaluate(() => OB.show(1));
await page.waitForTimeout(500);
await shot('02-ob2');
await page.evaluate(() => OB.show(2));
await page.waitForTimeout(500);
await shot('03-ob3');
await page.evaluate(() => Route.to('login'));
await page.waitForTimeout(400);
await shot('04-login');
await page.evaluate(() => Route.to('register'));
await page.waitForTimeout(400);
await shot('05-register');
await page.evaluate(() => Route.to('success'));
await page.waitForTimeout(400);
await shot('06-success');
await page.evaluate(() => App.demo());
await page.waitForTimeout(1200);
await shot('07-home');
await page.evaluate(() => Route.go('emis'));
await page.waitForTimeout(500);
await shot('08-emis');
await page.evaluate(() => Route.go('insights'));
await page.waitForTimeout(700);
await shot('09-insights');
await page.evaluate(() => Route.go('calendar'));
await page.waitForTimeout(500);
await shot('10-calendar');
await page.evaluate(() => Detail.open(Object.keys(Store.s.emis)[0]));
await page.waitForTimeout(500);
await shot('11-detail');
await page.evaluate(() => UI.closeOv('ov-detail'));
await page.evaluate(() => Edit2.open());
await page.waitForTimeout(500);
await shot('12-add');
await page.evaluate(() => Route.go('profile'));
await page.waitForTimeout(400);
await shot('13-profile');
await browser.close();
console.log('SHOTS DONE');
